import { Eye, EyeOff, KeyRound, Plus, ShieldCheck, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { apiFetch } from "../lib/api";

type VaultItem = { id:string; label:string; service:string; notes:string | null; created_at:string; updated_at:string };
type RevealedItem = { username:string; secret:string };

export default function CredentialsVault({ dark = false }: { dark?: boolean }) {
  const [items, setItems] = useState<VaultItem[]>([]); const [revealed, setRevealed] = useState<Record<string, RevealedItem>>({});
  const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  const [form, setForm] = useState({ label:"", service:"", username:"", secret:"", notes:"" });
  const panel = dark ? "border-white/10 bg-white/[0.045] text-white" : "border-slate-200 bg-white text-slate-900";
  const soft = dark ? "bg-white/5 text-slate-300" : "bg-slate-50 text-slate-600";
  const load = async () => { setLoading(true); try { const response = await apiFetch("/api/vault"); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to load your vault."); setItems(data.data ?? []); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to load your vault."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const reveal = async (id:string) => { if (revealed[id]) { setRevealed(current => { const next = { ...current }; delete next[id]; return next; }); return; } try { const response = await apiFetch(`/api/vault/${id}/reveal`, { method:"POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to reveal credential."); setRevealed(current => ({ ...current, [id]:data.data })); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to reveal credential."); } };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setNotice(""); try { const response = await apiFetch("/api/vault", { method:"POST", body:JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to save credential."); setOpen(false); setForm({ label:"", service:"", username:"", secret:"", notes:"" }); setRevealed({}); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to save credential."); } finally { setSaving(false); } };
  const remove = async (id:string) => { if (!window.confirm("Remove this saved credential? This cannot be undone.")) return; try { const response = await apiFetch(`/api/vault/${id}`, { method:"DELETE" }); if (!response.ok) { const data = await response.json(); throw new Error(data.message || "Unable to remove credential."); } setItems(current => current.filter(item => item.id !== id)); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to remove credential."); } };
  return <section className={`mt-6 rounded-2xl border p-5 shadow-sm ${panel}`}>
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-500/10 text-indigo-500"><KeyRound size={19}/></div><div><h2 className="font-semibold">Credentials Vault</h2><p className={dark ? "mt-1 text-sm text-slate-400" : "mt-1 text-sm text-slate-500"}>Private credentials, encrypted at rest and visible only to you.</p></div></div><button onClick={() => { setNotice(""); setOpen(true); }} className="inline-flex h-10 items-center gap-2 rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-700"><Plus size={16}/>Save credential</button></div>
    <div className={`mt-4 flex items-center gap-2 rounded-xl px-3 py-2 text-xs ${soft}`}><ShieldCheck size={15} className="text-emerald-500"/>Secrets are never stored in the browser. Reveal them only when needed.</div>
    {notice && <div role="status" className="mt-4 rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-600">{notice}</div>}
    <div className="mt-4 space-y-2">{loading && <div className={`rounded-xl p-4 text-center text-sm ${soft}`}>Opening your encrypted vault…</div>}{!loading && items.length === 0 && <div className={`rounded-xl border border-dashed p-7 text-center text-sm ${dark ? "border-white/15 text-slate-400" : "border-slate-200 text-slate-500"}`}>No credentials saved yet. Add a secure entry for a service you use.</div>}{items.map(item => <div key={item.id} className={`rounded-xl border p-3 ${dark ? "border-white/10 bg-black/10" : "border-slate-100 bg-slate-50/60"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-medium">{item.label}</div><div className={dark ? "mt-0.5 text-xs text-slate-400" : "mt-0.5 text-xs text-slate-500"}>{item.service}{item.notes ? ` · ${item.notes}` : ""}</div></div><div className="flex items-center gap-2"><button onClick={() => void reveal(item.id)} className={`inline-flex h-8 items-center gap-1.5 rounded-lg border px-2.5 text-xs font-semibold ${dark ? "border-white/10 hover:bg-white/10" : "border-slate-200 bg-white hover:bg-slate-50"}`}>{revealed[item.id] ? <EyeOff size={14}/> : <Eye size={14}/>} {revealed[item.id] ? "Hide" : "Reveal"}</button><button aria-label={`Remove ${item.label}`} onClick={() => void remove(item.id)} className="flex h-8 w-8 items-center justify-center rounded-lg text-rose-500 transition hover:bg-rose-500/10"><Trash2 size={15}/></button></div></div>{revealed[item.id] && <div className={`mt-3 grid gap-2 rounded-lg p-3 text-xs sm:grid-cols-2 ${soft}`}><div><span className="block text-[10px] font-bold uppercase tracking-wide opacity-60">Username</span><span className="mt-1 block break-all font-medium">{revealed[item.id].username}</span></div><div><span className="block text-[10px] font-bold uppercase tracking-wide opacity-60">Secret</span><span className="mt-1 block break-all font-medium">{revealed[item.id].secret}</span></div></div>}</div>)}</div>
    {open && <div className="fixed inset-0 z-[80] flex items-center justify-center p-4"><button aria-label="Close credential form" onClick={() => !saving && setOpen(false)} className="absolute inset-0 bg-slate-950/60 backdrop-blur-sm"/><form onSubmit={save} className="relative w-full max-w-lg rounded-2xl bg-white p-6 text-slate-900 shadow-2xl"><div className="mb-5 flex items-start justify-between"><div><h3 className="text-lg font-semibold">Save credential</h3><p className="mt-1 text-sm text-slate-500">This entry is encrypted before it is saved.</p></div><button type="button" aria-label="Close" onClick={() => setOpen(false)} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100"><X size={20}/></button></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Label<input required value={form.label} onChange={e => setForm({ ...form, label:e.target.value })} placeholder="Company GitHub" className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10"/></label><label className="text-sm font-medium">Service<input required value={form.service} onChange={e => setForm({ ...form, service:e.target.value })} placeholder="github.com" className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10"/></label></div><label className="mt-3 block text-sm font-medium">Username or email<input required value={form.username} onChange={e => setForm({ ...form, username:e.target.value })} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10"/></label><label className="mt-3 block text-sm font-medium">Password, API key, or secret<input required type="password" value={form.secret} onChange={e => setForm({ ...form, secret:e.target.value })} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10"/></label><label className="mt-3 block text-sm font-medium">Note <span className="font-normal text-slate-400">(optional)</span><textarea value={form.notes} onChange={e => setForm({ ...form, notes:e.target.value })} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10"/></label><button disabled={saving} className="mt-5 h-11 w-full rounded-xl bg-indigo-600 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-700 disabled:opacity-60">{saving ? "Encrypting…" : "Encrypt and save"}</button></form></div>}
  </section>;
}
