import { FormEvent, useState } from "react";
import { Code2, Eye, EyeOff, LockKeyhole } from "lucide-react";
import { apiUrl, AuthUser } from "../lib/api";

export default function DeveloperLogin({ onLoginSuccess }: { onLoginSuccess:(token:string, user:AuthUser)=>void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event:FormEvent) => { event.preventDefault(); setError(""); setLoading(true); try { const response = await fetch(`${apiUrl}/api/auth/login`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({email,password}) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to sign in"); if (data.user?.role !== "DEVELOPER") throw new Error("Use the main login for this account."); localStorage.setItem("zootechx_token", data.token); localStorage.setItem("zootechx_user", JSON.stringify(data.user)); onLoginSuccess(data.token, data.user); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to connect to the server"); } finally { setLoading(false); } };
  return <main className="login-shell min-h-screen overflow-hidden bg-[#1d2028] text-white"><div className="login-orb login-orb-one"/><div className="login-grid"/><div className="relative mx-auto flex min-h-screen max-w-md items-center px-5"><section className="login-panel w-full rounded-[28px] p-7 shadow-2xl sm:p-9"><div className="mb-8"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-50 text-indigo-600"><Code2 size={23}/></div><h1 className="text-2xl font-semibold text-slate-950">Developer login</h1><p className="mt-2 text-sm text-slate-500">Use the credentials provided by your Super Admin.</p></div><form onSubmit={submit} className="space-y-5"><input className="login-input" type="email" placeholder="Developer email" value={email} onChange={e=>setEmail(e.target.value)} required/><div className="relative"><input className="login-input pr-12" type={show?"text":"password"} placeholder="Temporary or secure password" value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{error&&<div className="rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-600">{error}</div>}<button className="login-submit" disabled={loading}>{loading?"Signing in…":"Open developer workspace"}<LockKeyhole size={16}/></button></form><a href="/" className="mt-6 block text-center text-xs text-indigo-600 hover:underline">Back to main login</a></section></div></main>;
}
