import React, { useEffect, useState } from "react";
import { apiFetch } from "../lib/api";
import AccountSettingsPanel from "./AccountSettingsPanel";

interface SubAdminDashboardProps { onLogout: () => void; }
type Client = { id: string; name: string; company: string | null; phone: string | null };
type Invoice = { id: string; invoice_number: string; total: string | number; paid_amount: string | number; due_date: string; client_name: string };
type Expense = { id: string; title: string; category: string; amount: string | number; expense_date: string | null; payment_method: string | null };
type Payment = { id: string; invoice_id: string; invoice_number: string; amount: string | number; method: string; created_at: string };
type Lead = { id: string; full_name: string; company: string | null; email: string | null; phone: string | null; source: string; status: string; notes: string | null; created_at: string };
type Followup = { id: string; lead_name: string; company: string | null; type: string; followup_date: string; followup_time: string | null; assigned_to: string | null; priority: string | null; status: string; notes: string | null };

export default function SubAdminDashboard({ onLogout }: SubAdminDashboardProps) {
  const [page, setPage] = useState("invoice"); const [dark, setDark] = useState(true); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  const [clients, setClients] = useState<Client[]>([]); const [invoices, setInvoices] = useState<Invoice[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [leads, setLeads] = useState<Lead[]>([]); const [followups, setFollowups] = useState<Followup[]>([]);
  const [clientForm, setClientForm] = useState({ name: "", company: "", phone: "" });
  const [invoiceForm, setInvoiceForm] = useState({ invoiceNumber: `INV-${Date.now().toString().slice(-6)}`, clientId: "", total: "", paidAmount: "0", dueDate: new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10) });
  const [expenseForm, setExpenseForm] = useState({ title: "", category: "", amount: "", expenseDate: new Date().toISOString().slice(0, 10), paymentMethod: "UPI", description: "" });
  const [paymentForm, setPaymentForm] = useState({ invoiceId: "", amount: "", method: "UPI" });
  const load = async () => { try { const [c, i, e, p, l, f] = await Promise.all([apiFetch("/api/clients"), apiFetch("/api/invoices"), apiFetch("/api/expenses"), apiFetch("/api/payments"), apiFetch("/api/leads"), apiFetch("/api/followups")]); const [cd, id, ed, pd, ld, fd] = await Promise.all([c.json(), i.json(), e.json(), p.json(), l.json(), f.json()]); if (c.ok) setClients(cd.data ?? []); if (i.ok) setInvoices(id.data ?? []); if (e.ok) setExpenses(ed.data ?? []); if (p.ok) setPayments(pd.data ?? []); if (l.ok) setLeads(ld.data ?? []); if (f.ok) setFollowups(fd.data ?? []); } catch { setNotice("Unable to load shared records. Check the backend connection."); } };
  useEffect(() => { void load(); const refresh = window.setInterval(() => void load(), 10_000); return () => window.clearInterval(refresh); }, []);
  const save = async (path: string, body: unknown, done: () => void) => { setSaving(true); try { const response = await apiFetch(path, { method: "POST", body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to save"); done(); setNotice("Saved successfully. Super Admin can now see this shared record."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to save"); } finally { setSaving(false); } };
  const shell = dark ? "bg-[#0a0a0f] text-white" : "bg-slate-50 text-slate-900"; const card = dark ? "bg-[#14141f] border-[#23233a]" : "bg-white border-slate-200"; const input = dark ? "bg-[#1c1c2e] border-[#2a2a40] text-white" : "bg-white border-slate-200 text-slate-900";
  const fields = (children: React.ReactNode) => <div className={`rounded-2xl border p-6 ${card}`}>{children}</div>;
  return <div className={`min-h-screen ${shell}`}><div className="mx-auto flex min-h-screen max-w-7xl"><aside className={`w-60 shrink-0 border-r p-4 ${dark ? "border-[#23233a] bg-[#0f0f1a]" : "border-slate-200 bg-white"}`}><div className="mb-8 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-600 to-violet-600 font-bold text-white">Z</div><div><div className="font-bold">ZootechX.ai</div><div className="text-xs text-slate-500">Sub Admin Portal</div></div></div>{[{ id: "leads", label: "Leads", icon: "◉" }, { id: "followups", label: "Follow-ups", icon: "◷" }, { id: "invoice", label: "New Invoice", icon: "＋" }, { id: "client", label: "Clients", icon: "◉" }, { id: "expense", label: "New Expense", icon: "₹" }, { id: "payment", label: "Record Payment", icon: "✓" }, { id: "records", label: "Shared Records", icon: "▦" }, { id: "settings", label: "Settings", icon: "⚙" }].map(item => <button key={item.id} onClick={() => setPage(item.id)} className={`mb-2 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-medium ${page === item.id ? "bg-indigo-600 text-white" : dark ? "text-slate-400 hover:bg-white/5" : "text-slate-600 hover:bg-slate-100"}`}><span>{item.icon}</span>{item.label}</button>)}</aside><main className="flex-1 p-7"><div className="mb-7 flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">{page === "leads" ? "Shared Leads" : page === "followups" ? "Shared Follow-up Queue" : page === "invoice" ? "Create Invoice" : page === "client" ? "Clients" : page === "expense" ? "Record Expense" : page === "payment" ? "Record Payment" : page === "records" ? "Shared Finance Records" : "Settings"}</h1><p className="mt-1 text-sm text-slate-500">Read-only customer work from Super Admin, plus shared finance records.</p></div><button onClick={() => setDark(!dark)} className={`rounded-xl border px-4 py-2 text-sm font-medium ${input}`}>{dark ? "☀ Light" : "☾ Dark"}</button></div>{notice && <div className="mb-5 rounded-xl border border-indigo-300 bg-indigo-50 px-4 py-3 text-sm text-indigo-700">{notice}</div>}
    {page === "leads" && fields(<><p className="mb-4 text-sm text-slate-500">Read-only live lead data. Sub Admin cannot edit leads.</p>{leads.map(lead => <div key={lead.id} className="grid gap-2 border-t border-slate-200 py-3 text-sm md:grid-cols-4"><span className="font-semibold">{lead.full_name}</span><span>{lead.company || "—"}</span><span>{lead.phone || lead.email || "—"}</span><span className="text-indigo-500">{lead.status.replaceAll("_", " ")}</span></div>)}{leads.length === 0 && <div className="py-8 text-center text-slate-500">No shared leads yet.</div>}</>)}
    {page === "followups" && fields(<><p className="mb-4 text-sm text-slate-500">Read-only follow-ups scheduled by Super Admin.</p>{followups.map(followup => <div key={followup.id} className="grid gap-2 border-t border-slate-200 py-3 text-sm md:grid-cols-4"><span className="font-semibold">{followup.lead_name}</span><span>{followup.type} · {followup.followup_date}</span><span>{followup.followup_time || "Time not set"}</span><span className="text-amber-500">{followup.status}</span></div>)}{followups.length === 0 && <div className="py-8 text-center text-slate-500">No Super Admin follow-ups have been scheduled yet.</div>}</>)}
    {page === "client" && fields(<form onSubmit={e => { e.preventDefault(); void save("/api/clients", { name: clientForm.name, company: clientForm.company || undefined, phone: clientForm.phone }, () => setClientForm({ name: "", company: "", phone: "" })); }} className="grid gap-4 md:grid-cols-3"><input required className={`h-11 rounded-xl border px-3 text-sm ${input}`} placeholder="Contact name" value={clientForm.name} onChange={e => setClientForm({ ...clientForm, name: e.target.value })}/><input className={`h-11 rounded-xl border px-3 text-sm ${input}`} placeholder="Business name" value={clientForm.company} onChange={e => setClientForm({ ...clientForm, company: e.target.value })}/><input required className={`h-11 rounded-xl border px-3 text-sm ${input}`} placeholder="Phone" value={clientForm.phone} onChange={e => setClientForm({ ...clientForm, phone: e.target.value })}/><button disabled={saving} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Add client</button></form>)}
    {page === "invoice" && fields(<form onSubmit={e => { e.preventDefault(); void save("/api/invoices", { invoiceNumber: invoiceForm.invoiceNumber, clientId: invoiceForm.clientId, total: Number(invoiceForm.total), paidAmount: Number(invoiceForm.paidAmount), dueDate: new Date(invoiceForm.dueDate).toISOString() }, () => setInvoiceForm({ invoiceNumber: `INV-${Date.now().toString().slice(-6)}`, clientId: "", total: "", paidAmount: "0", dueDate: new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10) })); }} className="grid gap-4 md:grid-cols-2"><input required className={`h-11 rounded-xl border px-3 text-sm ${input}`} placeholder="Invoice number" value={invoiceForm.invoiceNumber} onChange={e => setInvoiceForm({ ...invoiceForm, invoiceNumber: e.target.value })}/><select required className={`h-11 rounded-xl border px-3 text-sm ${input}`} value={invoiceForm.clientId} onChange={e => setInvoiceForm({ ...invoiceForm, clientId: e.target.value })}><option value="">Select client</option>{clients.map(client => <option key={client.id} value={client.id}>{client.company || client.name}</option>)}</select><input required min="1" type="number" className={`h-11 rounded-xl border px-3 text-sm ${input}`} placeholder="Invoice total" value={invoiceForm.total} onChange={e => setInvoiceForm({ ...invoiceForm, total: e.target.value })}/><input min="0" type="number" className={`h-11 rounded-xl border px-3 text-sm ${input}`} placeholder="Paid amount" value={invoiceForm.paidAmount} onChange={e => setInvoiceForm({ ...invoiceForm, paidAmount: e.target.value })}/><input required type="date" className={`h-11 rounded-xl border px-3 text-sm ${input}`} value={invoiceForm.dueDate} onChange={e => setInvoiceForm({ ...invoiceForm, dueDate: e.target.value })}/><button disabled={saving || clients.length === 0} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Create invoice</button>{clients.length === 0 && <p className="text-sm text-amber-600">Add a client first, then create the invoice.</p>}</form>)}
    {page === "expense" && fields(<form onSubmit={e => { e.preventDefault(); void save("/api/expenses", { ...expenseForm, amount: Number(expenseForm.amount) }, () => setExpenseForm({ title: "", category: "", amount: "", expenseDate: new Date().toISOString().slice(0, 10), paymentMethod: "UPI", description: "" })); }} className="grid gap-4 md:grid-cols-2"><input required className={`h-11 rounded-xl border px-3 text-sm ${input}`} placeholder="Expense title" value={expenseForm.title} onChange={e => setExpenseForm({ ...expenseForm, title: e.target.value })}/><input required className={`h-11 rounded-xl border px-3 text-sm ${input}`} placeholder="Category" value={expenseForm.category} onChange={e => setExpenseForm({ ...expenseForm, category: e.target.value })}/><input required min="1" type="number" className={`h-11 rounded-xl border px-3 text-sm ${input}`} placeholder="Amount" value={expenseForm.amount} onChange={e => setExpenseForm({ ...expenseForm, amount: e.target.value })}/><select className={`h-11 rounded-xl border px-3 text-sm ${input}`} value={expenseForm.paymentMethod} onChange={e => setExpenseForm({ ...expenseForm, paymentMethod: e.target.value })}><option>UPI</option><option>Cash</option><option>Bank Transfer</option><option>Card</option></select><input required type="date" className={`h-11 rounded-xl border px-3 text-sm ${input}`} value={expenseForm.expenseDate} onChange={e => setExpenseForm({ ...expenseForm, expenseDate: e.target.value })}/><textarea className={`min-h-24 rounded-xl border p-3 text-sm ${input}`} placeholder="Description" value={expenseForm.description} onChange={e => setExpenseForm({ ...expenseForm, description: e.target.value })}/><button disabled={saving} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Save expense</button></form>)}
    {page === "payment" && fields(<form onSubmit={e => { e.preventDefault(); void save("/api/payments", { ...paymentForm, amount: Number(paymentForm.amount) }, () => setPaymentForm({ invoiceId: "", amount: "", method: "UPI" })); }} className="grid gap-4 md:grid-cols-2"><select required className={`h-11 rounded-xl border px-3 text-sm ${input}`} value={paymentForm.invoiceId} onChange={e => setPaymentForm({ ...paymentForm, invoiceId: e.target.value })}><option value="">Select invoice</option>{invoices.map(invoice => <option key={invoice.id} value={invoice.id}>{invoice.invoice_number} · ₹{invoice.total}</option>)}</select><input required min="1" type="number" className={`h-11 rounded-xl border px-3 text-sm ${input}`} placeholder="Payment amount" value={paymentForm.amount} onChange={e => setPaymentForm({ ...paymentForm, amount: e.target.value })}/><select className={`h-11 rounded-xl border px-3 text-sm ${input}`} value={paymentForm.method} onChange={e => setPaymentForm({ ...paymentForm, method: e.target.value })}><option>UPI</option><option>Cash</option><option>Bank Transfer</option><option>Card</option></select><button disabled={saving} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Record payment</button></form>)}
    {page === "records" && <div className="space-y-5">{fields(<><h2 className="mb-3 font-semibold">Invoices</h2>{invoices.map(item => <div key={item.id} className="flex justify-between border-t border-slate-200 py-3 text-sm"><span>{item.invoice_number} · {item.client_name}</span><span>₹{item.total} · Paid ₹{item.paid_amount}</span></div>)}</>)}{fields(<><h2 className="mb-3 font-semibold">Expenses</h2>{expenses.map(item => <div key={item.id} className="flex justify-between border-t border-slate-200 py-3 text-sm"><span>{item.title} · {item.category}</span><span>₹{item.amount}</span></div>)}</>)}{fields(<><h2 className="mb-3 font-semibold">Payments</h2>{payments.map(item => <div key={item.id} className="flex justify-between border-t border-slate-200 py-3 text-sm"><span>{item.invoice_number} · {item.method}</span><span>₹{item.amount}</span></div>)}</>)}</div>}{page === "settings" && <AccountSettingsPanel onLogout={onLogout} dark={dark}/>}</main></div></div>;
}
